[package]
org = "smartticketing"
name = "payment_service"
version = "1.0.0"
# Update this to match your local Ballerina distribution version if different
distribution = "2201.9.0"
export = ["payment_service"]

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.3.0"

[[dependency]]
org = "ballerinax"  
name = "mongodb"
version = "1.8.0"