[package]
org = "smartticketing"
name = "admin_service"
version = "1.0.0"
distribution = "2201.9.0"
export = ["admin_service"]

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.3.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "1.8.0"
