[package]
org = "smartticketing"
name = "Ticketing_service"
version = "1.0.0"
distribution = "2201.9.0"
export = ["Ticketing_service"]

#dependencies for mongodb and kafka
[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "1.8.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.3.0"
